-- OpenInventory MVP Schema v1
-- Generated by Data Modeling Agent
-- Date: 2026-02-13

-- 1. Extensions
create extension if not exists "moddatetime" with schema "extensions";

-- 2. Tables

-- PROFILES
-- Extends Supabase auth.users
create table public.profiles (
    id uuid references auth.users(id) on delete cascade primary key,
    full_name text,
    avatar_url text,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- HOUSEHOLDS
-- The core tenant unit. For MVP, 1 user = 1 household (mostly).
create table public.households (
    id uuid default gen_random_uuid() primary key,
    name text not null,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- HOUSEHOLD_MEMBERS
-- Links users to households.
create table public.household_members (
    user_id uuid references public.profiles(id) on delete cascade not null,
    household_id uuid references public.households(id) on delete cascade not null,
    role text default 'member' check (role in ('owner', 'member', 'admin')),
    joined_at timestamptz default now() not null,
    primary key (user_id, household_id)
);

-- CATEGORIES
-- Can be global (household_id is null) or custom (household_id set).
create table public.categories (
    id uuid default gen_random_uuid() primary key,
    name text not null,
    description text,
    household_id uuid references public.households(id) on delete cascade, -- Nullable for global categories
    created_at timestamptz default now() not null
);

-- LOCATIONS
-- Physical places within a household (e.g., "Kitchen", "Garage").
create table public.locations (
    id uuid default gen_random_uuid() primary key,
    household_id uuid references public.households(id) on delete cascade not null,
    name text not null,
    description text,
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- INVENTORY_ITEMS
-- The main entity.
create table public.inventory_items (
    id uuid default gen_random_uuid() primary key,
    household_id uuid references public.households(id) on delete cascade not null,
    
    name text not null,
    description text,
    quantity numeric default 1 not null,
    unit text default 'pcs', -- e.g., 'kg', 'boxes', 'liters'
    
    category_id uuid references public.categories(id) on delete set null,
    location_id uuid references public.locations(id) on delete set null,
    
    status text default 'active' check (status in ('active', 'archived', 'consumed')),
    
    expiry_date date,
    purchase_date date,
    
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- ITEM_DOCUMENTS
-- Receipts, manuals, etc.
create table public.item_documents (
    id uuid default gen_random_uuid() primary key,
    item_id uuid references public.inventory_items(id) on delete cascade not null,
    household_id uuid references public.households(id) on delete cascade not null, -- Denormalized for RLS
    
    file_path text not null, -- Path in Supabase Storage
    file_name text not null, -- Original filename
    file_type text,          -- MIME type
    file_size bigint,
    
    created_at timestamptz default now() not null
);

-- ITEM_REMINDERS
-- Expiration warnings or custom reminders.
create table public.item_reminders (
    id uuid default gen_random_uuid() primary key,
    item_id uuid references public.inventory_items(id) on delete cascade not null,
    household_id uuid references public.households(id) on delete cascade not null, -- Denormalized for RLS
    
    reminder_date timestamptz not null,
    message text,
    is_completed boolean default false not null,
    snoozed_until timestamptz,
    
    created_at timestamptz default now() not null,
    updated_at timestamptz default now() not null
);

-- 3. Indexes
-- Optimize for household-scoped queries, which will be 99% of traffic.

create index idx_household_members_user on public.household_members(user_id);
create index idx_household_members_household on public.household_members(household_id);

create index idx_categories_household on public.categories(household_id);
create index idx_locations_household on public.locations(household_id);

create index idx_items_household on public.inventory_items(household_id);
create index idx_items_category on public.inventory_items(category_id);
create index idx_items_location on public.inventory_items(location_id);
create index idx_items_status on public.inventory_items(status);
create index idx_items_expiry on public.inventory_items(expiry_date);

create index idx_docs_item on public.item_documents(item_id);
create index idx_docs_household on public.item_documents(household_id);

create index idx_reminders_item on public.item_reminders(item_id);
create index idx_reminders_household on public.item_reminders(household_id);
create index idx_reminders_date on public.item_reminders(reminder_date) where is_completed = false;


-- 4. Triggers for updated_at

create trigger handle_updated_at_profiles
    before update on public.profiles
    for each row execute procedure extensions.moddatetime (updated_at);

create trigger handle_updated_at_households
    before update on public.households
    for each row execute procedure extensions.moddatetime (updated_at);

create trigger handle_updated_at_locations
    before update on public.locations
    for each row execute procedure extensions.moddatetime (updated_at);

create trigger handle_updated_at_items
    before update on public.inventory_items
    for each row execute procedure extensions.moddatetime (updated_at);

create trigger handle_updated_at_reminders
    before update on public.item_reminders
    for each row execute procedure extensions.moddatetime (updated_at);


-- 5. Auth Integration Trigger
-- Automatically create a profile when a new user signs up via Supabase Auth.

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

-- Drop if exists to ensure idempotency during dev
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

