-- OpenInventory MVP Security RLS v1
-- Generated by Security Agent
-- Date: 2026-02-13

-- 1. Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.households enable row level security;
alter table public.household_members enable row level security;
alter table public.categories enable row level security;
alter table public.locations enable row level security;
alter table public.inventory_items enable row level security;
alter table public.item_documents enable row level security;
alter table public.item_reminders enable row level security;

-- 2. Helper Functions
-- These functions help avoid infinite recursion in RLS policies and simplify logic.

-- Function to get all household IDs the current user belongs to.
-- Security Definer is crucial here to allow checking membership without hitting RLS recursion on household_members.
create or replace function public.get_my_household_ids()
returns uuid[]
language sql
stable
security definer
set search_path = public
as $$
  select array_agg(household_id)
  from public.household_members
  where user_id = auth.uid();
$$;

-- Function to check if current user is a member of a specific household
create or replace function public.is_household_member(lookup_household_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.household_members
    where household_id = lookup_household_id
    and user_id = auth.uid()
  );
$$;

-- Function to check if current user is an admin or owner of a specific household
create or replace function public.is_household_admin(lookup_household_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.household_members
    where household_id = lookup_household_id
    and user_id = auth.uid()
    and role in ('owner', 'admin')
  );
$$;

-- 3. Policies

-- PROFILES
-- Users can read/update their own profile.
create policy "Users can view own profile"
  on public.profiles for select
  using ( id = auth.uid() );

create policy "Users can update own profile"
  on public.profiles for update
  using ( id = auth.uid() );

-- Note: Insert is handled by trigger, but if we allow manual creation:
create policy "Users can insert own profile"
  on public.profiles for insert
  with check ( id = auth.uid() );


-- HOUSEHOLDS
-- Users can view households they belong to.
create policy "Members can view households"
  on public.households for select
  using ( id = any(public.get_my_household_ids()) );

-- Users can create households.
create policy "Users can create households"
  on public.households for insert
  with check ( true ); 
  -- Note: The creator must immediately add themselves as a member in the same transaction 
  -- or they won't be able to see it afterwards.

-- Only admins/owners can update household details.
create policy "Admins can update households"
  on public.households for update
  using ( public.is_household_admin(id) );

-- Only owners can delete (for MVP, maybe just admins too).
create policy "Admins can delete households"
  on public.households for delete
  using ( public.is_household_admin(id) );


-- HOUSEHOLD_MEMBERS
-- Users can view members of their households.
create policy "Users can view members of their households"
  on public.household_members for select
  using ( 
    household_id = any(public.get_my_household_ids()) 
    or user_id = auth.uid() -- Allow seeing self even if not in list yet (edge case)
  );

-- Users can join households (insert themselves). 
-- Realistically, this should be invite-only, but for MVP:
create policy "Users can join households"
  on public.household_members for insert
  with check ( 
    user_id = auth.uid() -- User adding themselves
    or public.is_household_admin(household_id) -- Admin adding someone else
  );

-- Admins can update roles.
create policy "Admins can update member roles"
  on public.household_members for update
  using ( public.is_household_admin(household_id) );

-- Users can leave, Admins can remove.
create policy "Users can leave or Admins can remove"
  on public.household_members for delete
  using ( 
    user_id = auth.uid() 
    or public.is_household_admin(household_id) 
  );


-- CATEGORIES
-- Global categories (household_id IS NULL) are visible to everyone.
-- Custom categories are visible to household members.
create policy "View categories"
  on public.categories for select
  using ( 
    household_id is null 
    or household_id = any(public.get_my_household_ids()) 
  );

-- Only members can create custom categories.
create policy "Create custom categories"
  on public.categories for insert
  with check ( 
    household_id is not null 
    and public.is_household_member(household_id) 
  );

-- Only members can update/delete custom categories.
create policy "Manage custom categories"
  on public.categories for all
  using ( 
    household_id is not null 
    and public.is_household_member(household_id) 
  );
-- Note: 'all' covers update/delete. Insert is covered above. Select is covered above.
-- To be precise for update/delete:
create policy "Update custom categories"
  on public.categories for update
  using ( 
    household_id is not null 
    and public.is_household_member(household_id) 
  );

create policy "Delete custom categories"
  on public.categories for delete
  using ( 
    household_id is not null 
    and public.is_household_member(household_id) 
  );


-- LOCATIONS
-- Standard household isolation.
create policy "View locations"
  on public.locations for select
  using ( household_id = any(public.get_my_household_ids()) );

create policy "Manage locations"
  on public.locations for all
  using ( household_id = any(public.get_my_household_ids()) )
  with check ( household_id = any(public.get_my_household_ids()) );


-- INVENTORY_ITEMS
-- Standard household isolation.
create policy "View items"
  on public.inventory_items for select
  using ( household_id = any(public.get_my_household_ids()) );

create policy "Manage items"
  on public.inventory_items for all
  using ( household_id = any(public.get_my_household_ids()) )
  with check ( household_id = any(public.get_my_household_ids()) );


-- ITEM_DOCUMENTS
-- Standard household isolation.
create policy "View documents"
  on public.item_documents for select
  using ( household_id = any(public.get_my_household_ids()) );

create policy "Manage documents"
  on public.item_documents for all
  using ( household_id = any(public.get_my_household_ids()) )
  with check ( household_id = any(public.get_my_household_ids()) );


-- ITEM_REMINDERS
-- Standard household isolation.
create policy "View reminders"
  on public.item_reminders for select
  using ( household_id = any(public.get_my_household_ids()) );

create policy "Manage reminders"
  on public.item_reminders for all
  using ( household_id = any(public.get_my_household_ids()) )
  with check ( household_id = any(public.get_my_household_ids()) );
